name: pulse_rate_monitor
description: Measure PPG using the phone's camera.

version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  charts_flutter: ^0.12.0
  wakelock: ^0.6.2
  flutter_better_camera: ^1.0.2+1
  flutter_riverpod: ^2.0.2
  percent_indicator: ^4.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/